name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Package executables
      run: npm run package:win

    - name: Create checksums
      run: |
        cd bin
        sha256sum * > checksums.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: executables
        path: bin/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ghec-sso.exe
          bin/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
